name: 🚀 Deploy to Namecheap via FTP

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🚀 Deploy React
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 🛠 Build Project
        run: |
          npm install
          npm run build

      - name: 📤 Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "dist/"
          server-dir: "public_html/"
